version: "3.3"
services:
  api:
    image: ipotemkin/movies_skypro_app:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    volumes:
      - ./data:/code/data  # to get to the database
    environment:
#      NO_RATE_LIMIT: "TRUE"  # switches off the rate limiting
      REDIS_HOST: "redis"
#    env_file:
#      - .env
    ports:
      - "8001:80"
    depends_on:
      - redis
#      redis:
#        condition: service_healthy
    command: uvicorn --host 0.0.0.0 --port 80 run:app --workers 4
  redis:
    image: redis:latest
